export { default as Arrow } from "./Arrow";
export { default as Bannerimage } from "./Bannerimage";
export { default as Cloud } from "./Cloud";
export { default as Contact } from "./Contact";
export { default as HomeImage } from "./HomeImage";
export { default as Icon } from "./Icon";
export { default as Iphone } from "./Iphone";
export { default as Success } from "./Success";
export { default as WhyImage } from "./WhyImage";
